FROM python:3.10

WORKDIR /frontend  # Đặt thư mục làm việc

# Copy chung file requirements.txt
COPY requirements.txt .
RUN pip install -r requirements.txt

# Cài đặt Chainlit nếu chưa có trong requirements.txt
RUN pip install chainlit

COPY frontend/ .

EXPOSE 8000
CMD ["chainlit", "run", "app.py"]
